use alopex_chirps_wire::node_id::NodeId;
use std::panic::catch_unwind;
use thiserror::Error;

/// A logical Durable message identity generated by Chirps.
///
/// The only public constructor uses the same CSPRNG-backed UUIDv4 generator as
/// [`NodeId`]. There is deliberately no byte/string parser or `From`
/// implementation, so a caller cannot select an arbitrary identity.
///
/// UUIDv4 contributes 122 random bits. For an aggregate of `N` generated
/// messages, the deployment collision upper bound is `N(N-1)/2^123`; for
/// `N <= 2^32` it is less than `2^-59`. This is an operational assumption, not
/// a runtime global counter or cap.
///
/// ```compile_fail
/// use alopex_chirps_core::durable::message::DurableMessageId;
/// let _ = DurableMessageId::from_bytes([0_u8; 16]);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DurableMessageId([u8; 16]);

impl DurableMessageId {
    /// Generates a fresh UUIDv4 identity using the platform CSPRNG.
    ///
    /// Failure of the underlying generator is returned instead of becoming a
    /// prepared request. No backend contact has occurred at this point.
    pub fn generate() -> Result<Self, MessageIdError> {
        generate_uuid_v4_bytes().map(Self)
    }

    /// Parses an identity already present in a checked Durable wire envelope.
    ///
    /// This rejects every UUID version and variant except RFC 4122 UUIDv4. The
    /// send preparation API does not accept this value, so parsing a received
    /// identity cannot be used to choose the identity of a new outbound send.
    #[allow(dead_code)] // consumed by the sibling delivery contract introduced in Task 2.2
    pub(crate) const fn try_from_wire_bytes(bytes: [u8; 16]) -> Result<Self, MessageIdError> {
        if bytes[6] & 0xf0 != 0x40 {
            return Err(MessageIdError::NotVersion4);
        }
        if bytes[8] & 0xc0 != 0x80 {
            return Err(MessageIdError::InvalidVariant);
        }
        Ok(Self(bytes))
    }

    /// Returns the canonical 16 UUID bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

/// A rejected logical message identity decoded from a Durable envelope.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum MessageIdError {
    /// The platform CSPRNG failed before producing a logical identity.
    #[error("durable message identity generator is unavailable")]
    GenerationUnavailable,
    /// Only UUID version 4 is valid for a logical message ID.
    #[error("durable message identity is not UUIDv4")]
    NotVersion4,
    /// Only the RFC 4122 UUID variant is valid.
    #[error("durable message identity has an invalid UUID variant")]
    InvalidVariant,
}

/// The identifier of one explicit send attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DurableAttemptId([u8; 16]);

impl DurableAttemptId {
    fn generate() -> Result<Self, MessageIdError> {
        generate_uuid_v4_bytes().map(Self)
    }

    /// Returns the canonical 16 UUID bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

fn generate_uuid_v4_bytes() -> Result<[u8; 16], MessageIdError> {
    catch_unwind(NodeId::new)
        .map(|id| *id.as_bytes())
        .map_err(|_| MessageIdError::GenerationUnavailable)
}

macro_rules! fixed_bytes {
    ($name:ident, $length:expr, $summary:literal) => {
        #[doc = $summary]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub struct $name([u8; $length]);

        impl $name {
            /// Wraps bytes produced by the responsible codec or verifier.
            #[must_use]
            pub const fn from_bytes(bytes: [u8; $length]) -> Self {
                Self(bytes)
            }

            /// Returns the fixed-width value.
            #[must_use]
            pub const fn as_bytes(&self) -> &[u8; $length] {
                &self.0
            }
        }
    };
}

fixed_bytes!(
    PayloadDigest,
    32,
    "A SHA-256 digest of the application payload."
);
fixed_bytes!(
    EnvelopeDigest,
    32,
    "A SHA-256 digest of the canonical Durable envelope."
);
fixed_bytes!(
    SessionFingerprint,
    32,
    "A provider-neutral fingerprint of an authenticated session binding."
);
fixed_bytes!(
    ResourceId,
    16,
    "The immutable UUID of one Durable broker resource incarnation."
);

/// The durable identity of a resource incarnation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ResourceEpoch {
    resource_id: ResourceId,
    epoch: u64,
}

impl ResourceEpoch {
    /// Creates the pair reported by a verified capability binding.
    #[must_use]
    pub const fn new(resource_id: ResourceId, epoch: u64) -> Self {
        Self { resource_id, epoch }
    }

    /// Returns the immutable resource UUID.
    #[must_use]
    pub const fn resource_id(self) -> ResourceId {
        self.resource_id
    }

    /// Returns the monotonically fenced resource epoch.
    #[must_use]
    pub const fn epoch(self) -> u64 {
        self.epoch
    }
}

/// The confirmation boundary requested for one send attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ConfirmationBoundary {
    /// Development-only broker acceptance; no exact location or sync claim.
    BrokerAccepted,
    /// Message and index have reached the compatible server's OS-sync boundary.
    OsSyncedAccepted,
}

/// Immutable routing metadata supplied before canonical encoding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DurableMessageRoute {
    source: NodeId,
    target: NodeId,
    generation: u64,
    partition: u32,
    ordering_key: Vec<u8>,
    routing_map_version: u32,
}

impl DurableMessageRoute {
    /// Creates an explicit route. Partition selection is owned by the adapter's
    /// deterministic router and is never recomputed for a prepared retry.
    #[must_use]
    pub fn new(
        source: NodeId,
        target: NodeId,
        generation: u64,
        partition: u32,
        ordering_key: Vec<u8>,
        routing_map_version: u32,
    ) -> Self {
        Self {
            source,
            target,
            generation,
            partition,
            ordering_key,
            routing_map_version,
        }
    }
}

/// Canonical content returned by a Durable envelope codec during preparation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CanonicalEnvelope {
    codec_version: u16,
    bytes: Vec<u8>,
    payload_digest: PayloadDigest,
    envelope_digest: EnvelopeDigest,
}

impl CanonicalEnvelope {
    /// Validates the state-free shape of canonical envelope output.
    pub fn try_new(
        codec_version: u16,
        bytes: Vec<u8>,
        payload_digest: PayloadDigest,
        envelope_digest: EnvelopeDigest,
    ) -> Result<Self, PrepareFailure> {
        if codec_version == 0 {
            return Err(PrepareFailure::UnsupportedCodecVersion(0));
        }
        if bytes.is_empty() {
            return Err(PrepareFailure::EmptyCanonicalEnvelope);
        }
        Ok(Self {
            codec_version,
            bytes,
            payload_digest,
            envelope_digest,
        })
    }
}

/// An immutable, retryable Durable request created before any backend contact.
///
/// Construction generates the message ID before invoking the canonical encoder.
/// The encoder sees that ID by reference, while no API accepts a caller-selected
/// ID. After construction every field is private and exposed read-only. Explicit
/// retry therefore reuses this value and changes only the attempt binding.
///
/// Chirps does not persist a producer outbox and does not automatically recover
/// sends after process failure. Applications that need transaction/publish
/// atomicity must persist their source record or prepared request themselves.
///
/// ```compile_fail
/// use alopex_chirps_core::durable::message::PreparedDurableSend;
/// fn change_partition(send: &mut PreparedDurableSend) {
///     send.partition = 4;
/// }
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PreparedDurableSend {
    message_id: DurableMessageId,
    source: NodeId,
    target: NodeId,
    generation: u64,
    partition: u32,
    ordering_key: Vec<u8>,
    routing_map_version: u32,
    codec_version: u16,
    canonical_bytes: Vec<u8>,
    payload_digest: PayloadDigest,
    envelope_digest: EnvelopeDigest,
}

/// Result of state-free preparation, before preflight or a send attempt.
pub type PrepareResult = Result<PreparedDurableSend, PrepareFailure>;

impl PreparedDurableSend {
    /// Generates a UUIDv4 ID, then asks the injected canonical encoder to bind
    /// that ID into immutable bytes and digests. No backend is contacted here.
    pub fn prepare<F>(route: DurableMessageRoute, encode: F) -> PrepareResult
    where
        F: FnOnce(&DurableMessageId) -> Result<CanonicalEnvelope, PrepareFailure>,
    {
        Self::prepare_with_id_generator(route, DurableMessageId::generate, encode)
    }

    fn prepare_with_id_generator<G, F>(
        route: DurableMessageRoute,
        generate_id: G,
        encode: F,
    ) -> PrepareResult
    where
        G: FnOnce() -> Result<DurableMessageId, MessageIdError>,
        F: FnOnce(&DurableMessageId) -> Result<CanonicalEnvelope, PrepareFailure>,
    {
        let message_id =
            generate_id().map_err(|_| PrepareFailure::IdentifierGenerationUnavailable)?;
        let canonical = encode(&message_id)?;
        Ok(Self {
            message_id,
            source: route.source,
            target: route.target,
            generation: route.generation,
            partition: route.partition,
            ordering_key: route.ordering_key,
            routing_map_version: route.routing_map_version,
            codec_version: canonical.codec_version,
            canonical_bytes: canonical.bytes,
            payload_digest: canonical.payload_digest,
            envelope_digest: canonical.envelope_digest,
        })
    }

    /// Returns the generated logical message identity.
    #[must_use]
    pub const fn message_id(&self) -> DurableMessageId {
        self.message_id
    }

    /// Returns the source node.
    #[must_use]
    pub const fn source(&self) -> NodeId {
        self.source
    }

    /// Returns the target node.
    #[must_use]
    pub const fn target(&self) -> NodeId {
        self.target
    }

    /// Returns the immutable inbox generation.
    #[must_use]
    pub const fn generation(&self) -> u64 {
        self.generation
    }

    /// Returns the explicit partition selected during preparation.
    #[must_use]
    pub const fn partition(&self) -> u32 {
        self.partition
    }

    /// Returns the ordering key bound into the route and envelope.
    #[must_use]
    pub fn ordering_key(&self) -> &[u8] {
        &self.ordering_key
    }

    /// Returns the deterministic routing-map version.
    #[must_use]
    pub const fn routing_map_version(&self) -> u32 {
        self.routing_map_version
    }

    /// Returns the canonical codec version.
    #[must_use]
    pub const fn codec_version(&self) -> u16 {
        self.codec_version
    }

    /// Returns the immutable canonical envelope bytes.
    #[must_use]
    pub fn canonical_bytes(&self) -> &[u8] {
        &self.canonical_bytes
    }

    /// Returns the payload digest.
    #[must_use]
    pub const fn payload_digest(&self) -> PayloadDigest {
        self.payload_digest
    }

    /// Returns the canonical envelope digest.
    #[must_use]
    pub const fn envelope_digest(&self) -> EnvelopeDigest {
        self.envelope_digest
    }
}

/// A typed state-free preparation failure.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum PrepareFailure {
    /// The configured CSPRNG could not generate a message identity.
    #[error("the message identity generator is unavailable")]
    IdentifierGenerationUnavailable,
    /// Codec version zero is reserved and cannot identify canonical bytes.
    #[error("unsupported durable codec version {0}")]
    UnsupportedCodecVersion(u16),
    /// A canonical envelope must contain at least its versioned framing.
    #[error("canonical durable envelope is empty")]
    EmptyCanonicalEnvelope,
    /// The canonical codec rejected the input before backend contact.
    #[error("canonical durable envelope encoding failed")]
    CanonicalEncoding,
}

/// A bounded provider-neutral reason why preflight did not start an attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum PreflightFailureKind {
    /// No Durable plane was configured; no fallback is attempted.
    #[error("durable plane is not configured")]
    Unconfigured,
    /// The configured Durable plane is temporarily unavailable.
    #[error("durable plane is unavailable")]
    Unavailable,
    /// The requested guarantee is unsupported by the verified capability.
    #[error("requested durable guarantee is unsupported")]
    Unsupported,
    /// Session or resource binding verification failed.
    #[error("durable session binding was rejected")]
    BindingRejected,
    /// Caller cancellation won before an attempt was started.
    #[error("durable preflight was cancelled")]
    Cancelled,
}

/// A failed preflight, explicitly outside the send-attempt state machine.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
#[error("durable preflight failed: {kind}")]
pub struct PreflightFailure {
    message_id: DurableMessageId,
    kind: PreflightFailureKind,
}

impl PreflightFailure {
    /// Records a preflight rejection for a prepared request.
    #[must_use]
    pub fn new(prepared: &PreparedDurableSend, kind: PreflightFailureKind) -> Self {
        Self {
            message_id: prepared.message_id,
            kind,
        }
    }

    /// Returns the prepared message identity.
    #[must_use]
    pub const fn message_id(&self) -> DurableMessageId {
        self.message_id
    }

    /// Returns the bounded failure classification.
    #[must_use]
    pub const fn kind(&self) -> PreflightFailureKind {
        self.kind
    }

    /// Preflight cannot own an attempt ID or session fingerprint.
    #[must_use]
    pub const fn binding(&self) -> AttemptBinding {
        AttemptBinding::not_attempted()
    }
}

/// Result of preflight, before an explicit send attempt starts.
pub type PreflightResult = Result<(), PreflightFailure>;

/// Attempt identity and the authenticated session/boundary it was started on.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct BoundAttempt {
    attempt_id: DurableAttemptId,
    message_id: DurableMessageId,
    envelope_digest: EnvelopeDigest,
    session_fingerprint: SessionFingerprint,
    requested_boundary: ConfirmationBoundary,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum AttemptBindingState {
    NotAttempted,
    Started(BoundAttempt),
    AppendInvoked(BoundAttempt),
}

/// Observable phase of an attempt binding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AttemptPhase {
    /// Preparation or preflight ended before an attempt ID was generated.
    NotAttempted,
    /// An attempt exists, but append-port invocation has not begun.
    Started,
    /// Append-port invocation has begun, so absence of an append is ambiguous.
    AppendInvoked,
}

/// Either `NotAttempted` or one exact request/session/boundary-bound attempt.
///
/// The private state prevents callers from fabricating a binding. Starting an
/// attempt consumes a prepared request by reference and stores its message ID
/// and envelope digest. Advancing to append invocation consumes the started
/// token, so `NotSubmitted` and post-invocation outcomes require distinct
/// values.
#[derive(Debug, PartialEq, Eq, Hash)]
pub struct AttemptBinding {
    state: AttemptBindingState,
}

impl AttemptBinding {
    /// Returns the sole binding valid before an attempt starts.
    #[must_use]
    pub const fn not_attempted() -> Self {
        Self {
            state: AttemptBindingState::NotAttempted,
        }
    }

    /// Starts a new attempt bound to one immutable prepared request.
    pub fn start(
        prepared: &PreparedDurableSend,
        session_fingerprint: SessionFingerprint,
        requested_boundary: ConfirmationBoundary,
    ) -> Result<Self, MessageIdError> {
        Ok(Self {
            state: AttemptBindingState::Started(BoundAttempt {
                attempt_id: DurableAttemptId::generate()?,
                message_id: prepared.message_id,
                envelope_digest: prepared.envelope_digest,
                session_fingerprint,
                requested_boundary,
            }),
        })
    }

    /// Consumes a started binding at the public ambiguity boundary.
    pub fn append_invoked(self) -> Result<Self, ResultShapeError> {
        match self.state {
            AttemptBindingState::Started(bound) => Ok(Self {
                state: AttemptBindingState::AppendInvoked(bound),
            }),
            AttemptBindingState::NotAttempted => Err(ResultShapeError::AttemptRequired),
            AttemptBindingState::AppendInvoked(_) => Err(ResultShapeError::PhaseMismatch),
        }
    }

    /// Returns true only after an attempt has started.
    #[must_use]
    pub const fn is_bound(&self) -> bool {
        !matches!(self.state, AttemptBindingState::NotAttempted)
    }

    /// Returns the phase represented by this linear token.
    #[must_use]
    pub const fn phase(&self) -> AttemptPhase {
        match self.state {
            AttemptBindingState::NotAttempted => AttemptPhase::NotAttempted,
            AttemptBindingState::Started(_) => AttemptPhase::Started,
            AttemptBindingState::AppendInvoked(_) => AttemptPhase::AppendInvoked,
        }
    }

    /// Returns the attempt ID, if an attempt has started.
    #[must_use]
    pub const fn attempt_id(&self) -> Option<DurableAttemptId> {
        match self.state {
            AttemptBindingState::NotAttempted => None,
            AttemptBindingState::Started(bound) | AttemptBindingState::AppendInvoked(bound) => {
                Some(bound.attempt_id)
            }
        }
    }

    /// Returns the bound session fingerprint, if any.
    #[must_use]
    pub const fn session_fingerprint(&self) -> Option<SessionFingerprint> {
        match self.state {
            AttemptBindingState::NotAttempted => None,
            AttemptBindingState::Started(bound) | AttemptBindingState::AppendInvoked(bound) => {
                Some(bound.session_fingerprint)
            }
        }
    }

    /// Returns the requested confirmation boundary, if an attempt has started.
    #[must_use]
    pub const fn requested_boundary(&self) -> Option<ConfirmationBoundary> {
        match self.state {
            AttemptBindingState::NotAttempted => None,
            AttemptBindingState::Started(bound) | AttemptBindingState::AppendInvoked(bound) => {
                Some(bound.requested_boundary)
            }
        }
    }

    fn require(
        self,
        prepared: &PreparedDurableSend,
        required_phase: AttemptPhase,
    ) -> Result<BoundAttempt, ResultShapeError> {
        let (phase, bound) = match self.state {
            AttemptBindingState::NotAttempted => return Err(ResultShapeError::AttemptRequired),
            AttemptBindingState::Started(bound) => (AttemptPhase::Started, bound),
            AttemptBindingState::AppendInvoked(bound) => (AttemptPhase::AppendInvoked, bound),
        };
        if phase != required_phase {
            return Err(ResultShapeError::PhaseMismatch);
        }
        if bound.message_id != prepared.message_id
            || bound.envelope_digest != prepared.envelope_digest
        {
            return Err(ResultShapeError::PreparedIdentityMismatch);
        }
        Ok(bound)
    }

    fn from_bound(bound: BoundAttempt, phase: AttemptPhase) -> Self {
        let state = match phase {
            AttemptPhase::NotAttempted => AttemptBindingState::NotAttempted,
            AttemptPhase::Started => AttemptBindingState::Started(bound),
            AttemptPhase::AppendInvoked => AttemptBindingState::AppendInvoked(bound),
        };
        Self { state }
    }

    fn duplicate_terminal(&self) -> Self {
        Self { state: self.state }
    }
}

/// A bounded provider-neutral failure after an attempt ID has been generated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum AttemptFailureKind {
    /// The session became unavailable.
    #[error("durable attempt became unavailable")]
    Unavailable,
    /// Owned transport failed.
    #[error("durable attempt transport failed")]
    Transport,
    /// A response failed protocol validation.
    #[error("durable attempt protocol validation failed")]
    Protocol,
    /// Caller cancellation ended observation of this attempt.
    #[error("durable attempt was cancelled")]
    Cancelled,
    /// Shutdown fenced or interrupted the attempt.
    #[error("durable attempt was fenced by shutdown")]
    Shutdown,
}

/// The exact boundary observed for a completed send operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DurableSendOutcome {
    /// Failed after attempt start but before append-port invocation.
    NotSubmitted(AttemptFailureKind),
    /// The standard broker success response was observed.
    BrokerAccepted,
    /// The compatible server's exact OS-synced response was verified.
    OsSyncedAccepted,
    /// Append was invoked but success could not be determined.
    Indeterminate(AttemptFailureKind),
}

/// A result from one started send attempt.
///
/// Every value is bound to an attempt. `NotSubmitted` means append-port
/// invocation never began. Once invocation begins, timeout, disconnect,
/// protocol error, cancellation, or shutdown is `Indeterminate`; it permits
/// zero or one broker append and is never retried automatically.
///
/// `BrokerAccepted` means only that the pinned standard broker returned normal
/// success. It deliberately contains no offset/index and makes no OS-sync,
/// restart-presence, delivery, replication, or exactly-once claim.
#[derive(Debug, PartialEq, Eq)]
pub struct DurableSendResult {
    message_id: DurableMessageId,
    binding: AttemptBinding,
    outcome: DurableSendOutcome,
    receipt: Option<DurableReceipt>,
}

impl DurableSendResult {
    /// Constructs a known-not-submitted attempt result.
    pub fn not_submitted(
        prepared: &PreparedDurableSend,
        binding: AttemptBinding,
        failure: AttemptFailureKind,
    ) -> Result<Self, ResultShapeError> {
        let bound = binding.require(prepared, AttemptPhase::Started)?;
        Ok(Self::attempt_result(
            prepared.message_id,
            bound,
            AttemptPhase::Started,
            DurableSendOutcome::NotSubmitted(failure),
        ))
    }

    /// Constructs development broker acceptance without an exact location.
    pub fn broker_accepted(
        prepared: &PreparedDurableSend,
        binding: AttemptBinding,
    ) -> Result<Self, ResultShapeError> {
        let bound = binding.require(prepared, AttemptPhase::AppendInvoked)?;
        if bound.requested_boundary != ConfirmationBoundary::BrokerAccepted {
            return Err(ResultShapeError::BoundaryMismatch);
        }
        Ok(Self::attempt_result(
            prepared.message_id,
            bound,
            AttemptPhase::AppendInvoked,
            DurableSendOutcome::BrokerAccepted,
        ))
    }

    /// Constructs an ambiguous result after append-port invocation.
    pub fn indeterminate(
        prepared: &PreparedDurableSend,
        binding: AttemptBinding,
        failure: AttemptFailureKind,
    ) -> Result<Self, ResultShapeError> {
        let bound = binding.require(prepared, AttemptPhase::AppendInvoked)?;
        Ok(Self::attempt_result(
            prepared.message_id,
            bound,
            AttemptPhase::AppendInvoked,
            DurableSendOutcome::Indeterminate(failure),
        ))
    }

    /// Constructs the only result variant allowed to carry an exact receipt.
    #[must_use]
    pub fn os_synced_accepted(receipt: DurableReceipt) -> Self {
        Self {
            message_id: receipt.message_id,
            binding: receipt.binding.duplicate_terminal(),
            outcome: DurableSendOutcome::OsSyncedAccepted,
            receipt: Some(receipt),
        }
    }

    fn attempt_result(
        message_id: DurableMessageId,
        bound: BoundAttempt,
        phase: AttemptPhase,
        outcome: DurableSendOutcome,
    ) -> Self {
        Self {
            message_id,
            binding: AttemptBinding::from_bound(bound, phase),
            outcome,
            receipt: None,
        }
    }

    /// Returns the immutable prepared message identity.
    #[must_use]
    pub const fn message_id(&self) -> DurableMessageId {
        self.message_id
    }

    /// Returns the exact attempt/session/boundary binding.
    #[must_use]
    pub const fn attempt_binding(&self) -> &AttemptBinding {
        &self.binding
    }

    /// Returns the boundary outcome.
    #[must_use]
    pub const fn outcome(&self) -> DurableSendOutcome {
        self.outcome
    }

    /// Returns an exact receipt only for `OsSyncedAccepted`.
    #[must_use]
    pub const fn receipt(&self) -> Option<&DurableReceipt> {
        self.receipt.as_ref()
    }
}

/// An exact receipt for the compatible server's OS-sync confirmation only.
///
/// This confirms that the message and index reached the operating system's sync
/// boundary at the stated location. It does not claim device power-loss
/// durability, replication, delivery, broker exactly-once, or an application
/// transaction. A lost response followed by explicit retry may append or
/// deliver the same logical message more than once.
#[derive(Debug, PartialEq, Eq)]
pub struct DurableReceipt {
    resource_epoch: ResourceEpoch,
    partition: u32,
    assigned_offset: u64,
    assigned_index: u64,
    message_id: DurableMessageId,
    envelope_digest: EnvelopeDigest,
    binding: AttemptBinding,
}

impl DurableReceipt {
    /// Constructs a receipt from fields already verified against one exact
    /// compatible-server response. Identity and digest are taken directly from
    /// the immutable prepared request; weak boundaries and partition mismatch
    /// are rejected.
    pub fn try_new(
        prepared: &PreparedDurableSend,
        binding: AttemptBinding,
        resource_epoch: ResourceEpoch,
        partition: u32,
        assigned_offset: u64,
        assigned_index: u64,
    ) -> Result<Self, ReceiptError> {
        let attempt = binding
            .require(prepared, AttemptPhase::AppendInvoked)
            .map_err(|error| match error {
                ResultShapeError::AttemptRequired => ReceiptError::AttemptRequired,
                ResultShapeError::PhaseMismatch => ReceiptError::AppendInvocationRequired,
                ResultShapeError::PreparedIdentityMismatch => {
                    ReceiptError::PreparedIdentityMismatch
                }
                ResultShapeError::BoundaryMismatch => ReceiptError::StrongBoundaryRequired,
            })?;
        if attempt.requested_boundary != ConfirmationBoundary::OsSyncedAccepted {
            return Err(ReceiptError::StrongBoundaryRequired);
        }
        if partition != prepared.partition {
            return Err(ReceiptError::PartitionMismatch {
                prepared: prepared.partition,
                received: partition,
            });
        }
        Ok(Self {
            resource_epoch,
            partition,
            assigned_offset,
            assigned_index,
            message_id: prepared.message_id,
            envelope_digest: prepared.envelope_digest,
            binding: AttemptBinding::from_bound(attempt, AttemptPhase::AppendInvoked),
        })
    }

    /// Returns the exact resource UUID/epoch pair.
    #[must_use]
    pub const fn resource_epoch(&self) -> ResourceEpoch {
        self.resource_epoch
    }

    /// Returns the explicit partition.
    #[must_use]
    pub const fn partition(&self) -> u32 {
        self.partition
    }

    /// Returns the assigned broker offset.
    #[must_use]
    pub const fn assigned_offset(&self) -> u64 {
        self.assigned_offset
    }

    /// Returns the assigned broker index.
    #[must_use]
    pub const fn assigned_index(&self) -> u64 {
        self.assigned_index
    }

    /// Returns the immutable logical message identity.
    #[must_use]
    pub const fn message_id(&self) -> DurableMessageId {
        self.message_id
    }

    /// Returns the canonical envelope digest.
    #[must_use]
    pub const fn envelope_digest(&self) -> EnvelopeDigest {
        self.envelope_digest
    }

    /// Returns the exact attempt/session/boundary binding.
    #[must_use]
    pub const fn attempt_binding(&self) -> &AttemptBinding {
        &self.binding
    }
}

/// A rejected combination of result fields.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum ResultShapeError {
    /// Send-attempt outcomes cannot carry `NotAttempted`.
    #[error("a send-attempt result requires a bound attempt")]
    AttemptRequired,
    /// The constructor did not receive the phase token for its boundary.
    #[error("the attempt is not at the required append-invocation phase")]
    PhaseMismatch,
    /// The binding belongs to a different prepared message or envelope.
    #[error("the attempt binding does not match the prepared request")]
    PreparedIdentityMismatch,
    /// The observed success does not match the requested boundary.
    #[error("the observed success does not match the requested boundary")]
    BoundaryMismatch,
}

/// A rejected exact-receipt shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum ReceiptError {
    /// Exact receipts require a started attempt.
    #[error("an exact receipt requires a bound attempt")]
    AttemptRequired,
    /// Exact receipts require proof that append-port invocation began.
    #[error("an exact receipt requires an append-invoked attempt")]
    AppendInvocationRequired,
    /// The binding belongs to a different prepared message or envelope.
    #[error("the exact receipt binding does not match the prepared request")]
    PreparedIdentityMismatch,
    /// Exact receipts exist only for the OS-synced boundary.
    #[error("an exact receipt requires the OS-synced boundary")]
    StrongBoundaryRequired,
    /// The response partition did not match the immutable prepared route.
    #[error("receipt partition {received} does not match prepared partition {prepared}")]
    PartitionMismatch { prepared: u32, received: u32 },
}

#[cfg(test)]
mod v07_task_2_1 {
    use super::*;
    use alopex_chirps_wire::node_id::NodeId;

    fn prepared() -> PreparedDurableSend {
        let route = DurableMessageRoute::new(
            NodeId::new(),
            NodeId::new(),
            7,
            3,
            b"account-42".to_vec(),
            2,
        );
        PreparedDurableSend::prepare(route, |_| {
            CanonicalEnvelope::try_new(
                1,
                b"canonical-envelope".to_vec(),
                PayloadDigest::from_bytes([0x11; 32]),
                EnvelopeDigest::from_bytes([0x22; 32]),
            )
        })
        .expect("valid prepared request")
    }

    fn started(
        prepared: &PreparedDurableSend,
        fingerprint_byte: u8,
        boundary: ConfirmationBoundary,
    ) -> AttemptBinding {
        AttemptBinding::start(
            prepared,
            SessionFingerprint::from_bytes([fingerprint_byte; 32]),
            boundary,
        )
        .expect("attempt ID generation")
    }

    fn invoked(
        prepared: &PreparedDurableSend,
        fingerprint_byte: u8,
        boundary: ConfirmationBoundary,
    ) -> AttemptBinding {
        started(prepared, fingerprint_byte, boundary)
            .append_invoked()
            .expect("started attempt advances to append invocation")
    }

    #[test]
    fn generated_message_ids_are_uuid_v4_only() {
        let id = DurableMessageId::generate().expect("message ID generation");
        let bytes = id.as_bytes();

        assert_eq!(bytes[6] & 0xf0, 0x40, "UUID version must be v4");
        assert_eq!(bytes[8] & 0xc0, 0x80, "UUID variant must be RFC 4122");
    }

    #[test]
    fn wire_message_ids_require_uuid_v4_version_and_variant() {
        let mut valid = [0_u8; 16];
        valid[6] = 0x40;
        valid[8] = 0x80;
        assert_eq!(
            DurableMessageId::try_from_wire_bytes(valid)
                .expect("valid received UUIDv4")
                .as_bytes(),
            &valid
        );

        let mut wrong_version = valid;
        wrong_version[6] = 0x50;
        assert_eq!(
            DurableMessageId::try_from_wire_bytes(wrong_version),
            Err(MessageIdError::NotVersion4)
        );

        let mut wrong_variant = valid;
        wrong_variant[8] = 0x40;
        assert_eq!(
            DurableMessageId::try_from_wire_bytes(wrong_variant),
            Err(MessageIdError::InvalidVariant)
        );
    }

    #[test]
    fn prepared_send_freezes_all_retry_identity_fields() {
        let original = prepared();
        let retry = original.clone();

        assert_eq!(retry.message_id(), original.message_id());
        assert_eq!(retry.source(), original.source());
        assert_eq!(retry.target(), original.target());
        assert_eq!(retry.generation(), 7);
        assert_eq!(retry.partition(), 3);
        assert_eq!(retry.ordering_key(), b"account-42");
        assert_eq!(retry.routing_map_version(), 2);
        assert_eq!(retry.codec_version(), 1);
        assert_eq!(retry.canonical_bytes(), b"canonical-envelope");
        assert_eq!(
            retry.payload_digest(),
            PayloadDigest::from_bytes([0x11; 32])
        );
        assert_eq!(
            retry.envelope_digest(),
            EnvelopeDigest::from_bytes([0x22; 32])
        );
    }

    #[test]
    fn malformed_prepared_metadata_is_a_prepare_failure() {
        let route = DurableMessageRoute::new(
            NodeId::new(),
            NodeId::new(),
            7,
            3,
            b"account-42".to_vec(),
            2,
        );

        assert_eq!(
            PreparedDurableSend::prepare(route, |_| {
                CanonicalEnvelope::try_new(
                    1,
                    Vec::new(),
                    PayloadDigest::from_bytes([0x11; 32]),
                    EnvelopeDigest::from_bytes([0x22; 32]),
                )
            }),
            Err(PrepareFailure::EmptyCanonicalEnvelope)
        );
    }

    #[test]
    fn identifier_generation_failure_is_a_prepare_failure() {
        let route = DurableMessageRoute::new(
            NodeId::new(),
            NodeId::new(),
            7,
            3,
            b"account-42".to_vec(),
            2,
        );

        let result = PreparedDurableSend::prepare_with_id_generator(
            route,
            || Err(MessageIdError::GenerationUnavailable),
            |_| panic!("canonical encoder must not run after RNG failure"),
        );
        assert_eq!(result, Err(PrepareFailure::IdentifierGenerationUnavailable));
    }

    #[test]
    fn preflight_failure_is_not_a_send_attempt() {
        let prepared = prepared();
        let failure = PreflightFailure::new(&prepared, PreflightFailureKind::Unavailable);
        let result: PreflightResult = Err(failure.clone());
        let Err(actual) = result else {
            panic!("preflight failure unexpectedly became ready");
        };

        assert_eq!(actual.binding(), AttemptBinding::not_attempted());
        assert_eq!(failure.kind(), PreflightFailureKind::Unavailable);
    }

    #[test]
    fn attempt_outcomes_require_a_bound_attempt() {
        let prepared = prepared();
        let error = DurableSendResult::not_submitted(
            &prepared,
            AttemptBinding::not_attempted(),
            AttemptFailureKind::Unavailable,
        )
        .unwrap_err();

        assert_eq!(error, ResultShapeError::AttemptRequired);
    }

    #[test]
    fn broker_acceptance_has_no_exact_location_or_receipt() {
        let prepared = prepared();
        let binding = invoked(&prepared, 0x33, ConfirmationBoundary::BrokerAccepted);
        let result =
            DurableSendResult::broker_accepted(&prepared, binding).expect("matching weak boundary");

        assert_eq!(result.outcome(), DurableSendOutcome::BrokerAccepted);
        assert!(result.attempt_binding().is_bound());
        assert!(result.receipt().is_none());
    }

    #[test]
    fn broker_acceptance_rejects_a_strong_requested_boundary() {
        let prepared = prepared();
        let binding = invoked(&prepared, 0x34, ConfirmationBoundary::OsSyncedAccepted);

        assert_eq!(
            DurableSendResult::broker_accepted(&prepared, binding),
            Err(ResultShapeError::BoundaryMismatch)
        );
    }

    #[test]
    fn attempt_failures_preserve_boundary_and_never_gain_a_receipt() {
        let prepared = prepared();
        let not_submitted_binding =
            started(&prepared, 0x35, ConfirmationBoundary::OsSyncedAccepted);
        let not_submitted_attempt = not_submitted_binding.attempt_id();
        let not_submitted = DurableSendResult::not_submitted(
            &prepared,
            not_submitted_binding,
            AttemptFailureKind::Unavailable,
        )
        .expect("started attempt");
        assert_eq!(
            not_submitted.outcome(),
            DurableSendOutcome::NotSubmitted(AttemptFailureKind::Unavailable)
        );
        assert_eq!(
            not_submitted.attempt_binding().attempt_id(),
            not_submitted_attempt
        );
        assert_eq!(
            not_submitted.attempt_binding().phase(),
            AttemptPhase::Started
        );
        assert!(not_submitted.receipt().is_none());

        let indeterminate_binding =
            invoked(&prepared, 0x36, ConfirmationBoundary::OsSyncedAccepted);
        let indeterminate_attempt = indeterminate_binding.attempt_id();
        let indeterminate = DurableSendResult::indeterminate(
            &prepared,
            indeterminate_binding,
            AttemptFailureKind::Cancelled,
        )
        .expect("started attempt");
        assert_eq!(
            indeterminate.outcome(),
            DurableSendOutcome::Indeterminate(AttemptFailureKind::Cancelled)
        );
        assert_eq!(
            indeterminate.attempt_binding().attempt_id(),
            indeterminate_attempt
        );
        assert_eq!(
            indeterminate.attempt_binding().phase(),
            AttemptPhase::AppendInvoked
        );
        assert!(indeterminate.receipt().is_none());
    }

    #[test]
    fn attempt_phase_and_prepared_identity_are_enforced() {
        let prepared_send = prepared();
        let other = prepared();

        assert_eq!(
            DurableSendResult::indeterminate(
                &prepared_send,
                started(&prepared_send, 0x37, ConfirmationBoundary::OsSyncedAccepted,),
                AttemptFailureKind::Transport,
            ),
            Err(ResultShapeError::PhaseMismatch)
        );
        assert_eq!(
            DurableSendResult::not_submitted(
                &prepared_send,
                invoked(&prepared_send, 0x38, ConfirmationBoundary::OsSyncedAccepted,),
                AttemptFailureKind::Transport,
            ),
            Err(ResultShapeError::PhaseMismatch)
        );
        assert_eq!(
            DurableSendResult::not_submitted(
                &other,
                started(&prepared_send, 0x39, ConfirmationBoundary::OsSyncedAccepted,),
                AttemptFailureKind::Transport,
            ),
            Err(ResultShapeError::PreparedIdentityMismatch)
        );
    }

    #[test]
    fn only_strong_boundary_can_construct_an_exact_receipt() {
        let prepared = prepared();
        let weak_binding = invoked(&prepared, 0x44, ConfirmationBoundary::BrokerAccepted);
        let epoch = ResourceEpoch::new(ResourceId::from_bytes([0x55; 16]), 9);

        assert_eq!(
            DurableReceipt::try_new(&prepared, weak_binding, epoch, 3, 41, 42),
            Err(ReceiptError::StrongBoundaryRequired)
        );
        assert_eq!(
            DurableReceipt::try_new(&prepared, AttemptBinding::not_attempted(), epoch, 3, 41, 42,),
            Err(ReceiptError::AttemptRequired)
        );
    }

    #[test]
    fn strong_receipt_binds_exact_identity_attempt_and_location() {
        let prepared = prepared();
        let binding = invoked(&prepared, 0x66, ConfirmationBoundary::OsSyncedAccepted);
        let attempt_id = binding.attempt_id();
        let epoch = ResourceEpoch::new(ResourceId::from_bytes([0x77; 16]), 10);
        let receipt = DurableReceipt::try_new(&prepared, binding, epoch, 3, 91, 92)
            .expect("strong exact receipt");
        let result = DurableSendResult::os_synced_accepted(receipt);

        assert_eq!(result.outcome(), DurableSendOutcome::OsSyncedAccepted);
        assert_eq!(result.message_id(), prepared.message_id());
        assert_eq!(result.attempt_binding().attempt_id(), attempt_id);
        let receipt = result.receipt().expect("strong result owns exact receipt");
        assert_eq!(result.attempt_binding(), receipt.attempt_binding());
        assert_eq!(receipt.resource_epoch(), epoch);
        assert_eq!(receipt.partition(), 3);
        assert_eq!(receipt.assigned_offset(), 91);
        assert_eq!(receipt.assigned_index(), 92);
        assert_eq!(receipt.message_id(), prepared.message_id());
        assert_eq!(receipt.envelope_digest(), prepared.envelope_digest());
    }

    #[test]
    fn exact_receipt_rejects_a_different_partition() {
        let prepared = prepared();
        let binding = invoked(&prepared, 0x88, ConfirmationBoundary::OsSyncedAccepted);
        let epoch = ResourceEpoch::new(ResourceId::from_bytes([0x99; 16]), 11);

        assert_eq!(
            DurableReceipt::try_new(&prepared, binding, epoch, 4, 1, 1),
            Err(ReceiptError::PartitionMismatch {
                prepared: 3,
                received: 4,
            })
        );
    }

    #[test]
    fn retry_reuses_prepared_identity_but_starts_a_new_attempt() {
        let prepared = prepared();
        let first = started(&prepared, 0xaa, ConfirmationBoundary::OsSyncedAccepted);
        let second = started(&prepared, 0xaa, ConfirmationBoundary::OsSyncedAccepted);

        assert_eq!(prepared.clone().message_id(), prepared.message_id());
        assert_ne!(first.attempt_id(), second.attempt_id());
    }
}
