[package]
name = "chirps-gossip-swim"
version = "0.1.0"
edition = "2024"

[dependencies]
chirps-wire = { path = "../chirps-wire" }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
rand = "0.8"
async-trait = "0.1"
tokio = { version = "1.35", features = ["time", "macros", "rt", "rt-multi-thread", "sync"] }
thiserror = "1.0"
