ARG RUST_IMAGE=rust:1.96-bookworm
FROM ${RUST_IMAGE} AS build
ARG SOURCE_SHA=unknown
WORKDIR /src
COPY . .
RUN cargo build --locked --release -p chirps-multi-raft-perf

FROM debian:bookworm-slim
ARG SOURCE_SHA=unknown
RUN apt-get update \
    && apt-get install --no-install-recommends -y ca-certificates iproute2 iputils-ping procps util-linux \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --create-home --uid 10001 --shell /usr/sbin/nologin chirps
COPY --from=build /src/target/release/chirps-multi-raft-perf /usr/local/bin/chirps-multi-raft-perf
LABEL org.opencontainers.image.revision="${SOURCE_SHA}"
USER chirps
ENTRYPOINT ["/usr/local/bin/chirps-multi-raft-perf"]
